language: scala
scala:
- 2.11.11
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.sbt"
  - "$HOME/.ivy2"
deploy:
  provider: script
  script: ./travis-deploy.sh
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
env:
  global:
  - secure: LWBjoTTL2fTu//Skbb4zZuC+i/rk7DVPVqo4vXmCUYQZGP8rAqexjareleCMqJwpNLLkUkT+31nj/ahVhDn2nQxiN8B2M2ctkDVjFokqo2fr/8a39HdxyS5Vy2WIpg8UdDVwsfRD85lusDNCYpqlXDNgpkmJNBZf0TR6mIc1VZ+0bJsmpyG5xTTFsoInJjLuBEwU4dkW68DKVbkXFr/Z97zhLrrkb+C35og4Ze+bjczhRwyxjq6TFAbD0tgQAhFruhJ017s7XklN/7anjg/+5vJ3DrSWIdN1zcGvodOFqHjsSukPsoLsQgyAJ0svGdnMHMg2Xgue8N9fQxPtF+pfHWhr1mFGNBCOUgbYvhLxG7BMdk8wY63TqUBLdoRA9sa/BXEYoi0cEEVS6U9zZOdJb2MID6q76n4DXdN8FRaklJsYS9EkQvpUNARjo6Efbmz+IO49Zq2Yb93w7oMgmsslloS7hzVwF0/jBEh94BzP5mopOwuA34L/ULS7Ya9o13YxxpMN7W+XTe+WcIOopTrbnzOsdIKIoar4055tilfBAJUiFzlBJMJSJjREzV75CJrJavNdSXSejeEx4zqpHC27LMuK0QyNkETMBri/XK/lKy8M+sS6ClpT2OYrNRnO7blCCkRQKtejjF5gHdhNPbITo15elhQtgKq3v7Va3/jj99A=
  - secure: hA7+3hYk0qvzIpHMU3NGwr6EeNtiX8vswThIfYaMj76tteter2tmzudlaRktt8K9aNhejIUDIQAzk4ataOGZv9oCm9NHEm5TydrqQaSfMPRxIY1/k74gBXyvcNOMp4emmczOE5A0rjaODiS9zFjGKpLMoB58zhZgV1suFPTGIHxeibWieroPayEIAbU25wvspmdessGYGuuN7q+Dw7c9qHOzwsmgfdoAwBKRe+0u/P/s6dXQJqBCvQGWa56JcGwTjYAjTD1kTv1861g1yXm3tTBDqF1tm4+C378kbL3T39Yq4aNiLdiC0IqM7gh07MISt13CONxNQUzC862JjfEIeWpPm9VDsrfrMsbeDJyzzryq5w7g6KJ06T5wWChMteIHQNYWXcfnpmcCrmXSM7KmcWjqc+1Voacuvr6g6z2EGnP4EFNI64x13dIHjk9cNXw7Lmg0dHzc4gS2rlpTjDCujo6irM9G+zcFpXDYw4ocq/fX6nSbmwhbYtZByQupsoszOSEkIxEFoHi11XMPMVzXcfvRGIeXTodMYbDWIDrcB9sVSh4xDMT4csmD6B3l57yt5ReXmpfKK+RAJ8Ew88TlGvCsCBroWUoCofT7aJnyHGuQ//3QwaOZPq1nAa2fCl3KvlCinsFTE6f6CW2OtUPw2mL2wWLtWe9OOk8wKnzyqCA=
